# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Julián Perelli
tagline:          "Yet another web engineer's blog"
description:      'The personal website of Julián Perelli'
url:              jperelli.com.ar

author:
  name:           'Julián Perelli'
  url:            https://jperelli.com.ar/

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           github.com/jperelli/jperelli.github.io

# This is the list of pages to incldue in the header of the website.
pages_list:       {'About':'/about','Archive':'/archive','Feed':'/atom.xml'}

